/* automatically generated by rust-bindgen 0.59.1 */

extern "C" {
    #[link_name = "\u{1}__Z6c_mathiii"]
    pub fn c_math(
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        z: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
