/* automatically generated by rust-bindgen 0.59.1 */

extern "C" {
    #[link_name = "\u{1}__Z8c_randomii"]
    pub fn c_random(x: ::std::os::raw::c_int, y: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
